print("Hello, World!")
print("This is a sample Python script.")
print("You can add more code here to perform various tasks.")
print("Feel free to modify and expand this script as needed.")
print("Remember to save your changes before running the script.")
print("Goodbye, World!")
print("This is the end of the sample script.")
print("Thank you for using this sample script.")
print("Have a great day!")